// Built-in exercise & machine library.
// track: 'wr' weight x reps | 'br' bodyweight reps (weight optional, e.g. weighted pull-up)
//        'dur' timed hold    | 'cardio' duration + distance
// mech:  'comp' compound | 'iso' isolation

export const MUSCLES = {
  chest: 'Chest', lats: 'Lats', upperback: 'Upper Back', traps: 'Traps',
  lowerback: 'Lower Back', shoulders: 'Shoulders', reardelts: 'Rear Delts',
  biceps: 'Biceps', triceps: 'Triceps', forearms: 'Forearms',
  quads: 'Quads', hamstrings: 'Hamstrings', glutes: 'Glutes', calves: 'Calves',
  adductors: 'Adductors', abductors: 'Abductors',
  abs: 'Abs', obliques: 'Obliques', neck: 'Neck',
  fullbody: 'Full Body', cardio: 'Cardio',
};

export const EQUIPMENT = {
  barbell: 'Barbell', dumbbell: 'Dumbbell', machine: 'Machine', cable: 'Cable',
  smith: 'Smith Machine', bodyweight: 'Bodyweight', kettlebell: 'Kettlebell',
  band: 'Band', ezbar: 'EZ Bar', trapbar: 'Trap Bar', plate: 'Plate',
  medball: 'Med Ball', sled: 'Sled', cardio: 'Cardio Machine', other: 'Other',
};

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const E = (name, equipment, primary, secondary = [], mech = 'iso', track = 'wr') => ({
  id: slug(name), name, equipment, primary, secondary, mech, track, custom: false, archived: false,
});

export const EXERCISE_LIBRARY = [
  // ---------- CHEST ----------
  E('Barbell Bench Press', 'barbell', 'chest', ['triceps', 'shoulders'], 'comp'),
  E('Incline Barbell Bench Press', 'barbell', 'chest', ['shoulders', 'triceps'], 'comp'),
  E('Decline Barbell Bench Press', 'barbell', 'chest', ['triceps'], 'comp'),
  E('Paused Bench Press', 'barbell', 'chest', ['triceps', 'shoulders'], 'comp'),
  E('Floor Press', 'barbell', 'chest', ['triceps'], 'comp'),
  E('Dumbbell Bench Press', 'dumbbell', 'chest', ['triceps', 'shoulders'], 'comp'),
  E('Incline Dumbbell Press', 'dumbbell', 'chest', ['shoulders', 'triceps'], 'comp'),
  E('Decline Dumbbell Press', 'dumbbell', 'chest', ['triceps'], 'comp'),
  E('Dumbbell Fly', 'dumbbell', 'chest', [], 'iso'),
  E('Incline Dumbbell Fly', 'dumbbell', 'chest', ['shoulders'], 'iso'),
  E('Dumbbell Pullover', 'dumbbell', 'chest', ['lats'], 'iso'),
  E('Cable Crossover', 'cable', 'chest', [], 'iso'),
  E('Cable Chest Press', 'cable', 'chest', ['triceps', 'shoulders'], 'comp'),
  E('Low-to-High Cable Fly', 'cable', 'chest', ['shoulders'], 'iso'),
  E('High-to-Low Cable Fly', 'cable', 'chest', [], 'iso'),
  E('Seated Cable Fly', 'cable', 'chest', [], 'iso'),
  E('Pec Deck Machine', 'machine', 'chest', [], 'iso'),
  E('Incline Chest Fly Machine', 'machine', 'chest', ['shoulders'], 'iso'),
  E('Decline Chest Fly Machine', 'machine', 'chest', [], 'iso'),
  E('Chest Press Machine', 'machine', 'chest', ['triceps', 'shoulders'], 'comp'),
  E('Incline Chest Press Machine', 'machine', 'chest', ['shoulders', 'triceps'], 'comp'),
  E('Decline Chest Press Machine', 'machine', 'chest', ['triceps'], 'comp'),
  E('Smith Machine Bench Press', 'smith', 'chest', ['triceps', 'shoulders'], 'comp'),
  E('Smith Machine Incline Press', 'smith', 'chest', ['shoulders', 'triceps'], 'comp'),
  E('Push-Up', 'bodyweight', 'chest', ['triceps', 'shoulders'], 'comp', 'br'),
  E('Incline Push-Up', 'bodyweight', 'chest', ['triceps'], 'comp', 'br'),
  E('Decline Push-Up', 'bodyweight', 'chest', ['shoulders', 'triceps'], 'comp', 'br'),
  E('Deficit Push-Up', 'bodyweight', 'chest', ['triceps'], 'comp', 'br'),
  E('Chest Dip', 'bodyweight', 'chest', ['triceps', 'shoulders'], 'comp', 'br'),
  E('Assisted Dip Machine', 'machine', 'chest', ['triceps'], 'comp'),
  E('Svend Press', 'plate', 'chest', [], 'iso'),
  E('Landmine Chest Press', 'barbell', 'chest', ['shoulders', 'triceps'], 'comp'),
  E('Band Chest Fly', 'band', 'chest', [], 'iso'),

  // ---------- BACK / LATS ----------
  E('Conventional Deadlift', 'barbell', 'lowerback', ['hamstrings', 'glutes', 'traps', 'upperback'], 'comp'),
  E('Sumo Deadlift', 'barbell', 'glutes', ['quads', 'lowerback', 'traps'], 'comp'),
  E('Trap Bar Deadlift', 'trapbar', 'quads', ['glutes', 'lowerback', 'traps'], 'comp'),
  E('Deficit Deadlift', 'barbell', 'lowerback', ['hamstrings', 'glutes'], 'comp'),
  E('Rack Pull', 'barbell', 'traps', ['lowerback', 'upperback'], 'comp'),
  E('Barbell Bent-Over Row', 'barbell', 'upperback', ['lats', 'biceps'], 'comp'),
  E('Pendlay Row', 'barbell', 'upperback', ['lats', 'biceps'], 'comp'),
  E('Yates Row', 'barbell', 'lats', ['upperback', 'biceps'], 'comp'),
  E('T-Bar Row', 'barbell', 'upperback', ['lats', 'biceps'], 'comp'),
  E('Chest-Supported T-Bar Row', 'machine', 'upperback', ['lats', 'biceps'], 'comp'),
  E('Seal Row', 'barbell', 'upperback', ['lats', 'biceps'], 'comp'),
  E('Meadows Row', 'barbell', 'lats', ['upperback', 'biceps'], 'comp'),
  E('Single-Arm Dumbbell Row', 'dumbbell', 'lats', ['upperback', 'biceps'], 'comp'),
  E('Chest-Supported Dumbbell Row', 'dumbbell', 'upperback', ['lats', 'biceps'], 'comp'),
  E('Kroc Row', 'dumbbell', 'lats', ['upperback', 'forearms'], 'comp'),
  E('Seated Cable Row', 'cable', 'upperback', ['lats', 'biceps'], 'comp'),
  E('Wide-Grip Seated Cable Row', 'cable', 'upperback', ['reardelts', 'lats'], 'comp'),
  E('Single-Arm Cable Row', 'cable', 'lats', ['upperback', 'biceps'], 'comp'),
  E('Machine Row', 'machine', 'upperback', ['lats', 'biceps'], 'comp'),
  E('Iso-Lateral Row', 'machine', 'upperback', ['lats', 'biceps'], 'comp'),
  E('Smith Machine Row', 'smith', 'upperback', ['lats', 'biceps'], 'comp'),
  E('Inverted Row', 'bodyweight', 'upperback', ['lats', 'biceps'], 'comp', 'br'),
  E('Lat Pulldown', 'cable', 'lats', ['biceps', 'upperback'], 'comp'),
  E('Wide-Grip Lat Pulldown', 'cable', 'lats', ['upperback'], 'comp'),
  E('Close-Grip Lat Pulldown', 'cable', 'lats', ['biceps'], 'comp'),
  E('Reverse-Grip Lat Pulldown', 'cable', 'lats', ['biceps'], 'comp'),
  E('Single-Arm Lat Pulldown', 'cable', 'lats', ['biceps'], 'comp'),
  E('Straight-Arm Pulldown', 'cable', 'lats', [], 'iso'),
  E('Machine Pulldown', 'machine', 'lats', ['biceps'], 'comp'),
  E('Iso-Lateral Pulldown', 'machine', 'lats', ['biceps'], 'comp'),
  E('Pull-Up', 'bodyweight', 'lats', ['biceps', 'upperback'], 'comp', 'br'),
  E('Chin-Up', 'bodyweight', 'lats', ['biceps'], 'comp', 'br'),
  E('Neutral-Grip Pull-Up', 'bodyweight', 'lats', ['biceps'], 'comp', 'br'),
  E('Assisted Pull-Up Machine', 'machine', 'lats', ['biceps'], 'comp'),
  E('Back Extension', 'bodyweight', 'lowerback', ['glutes', 'hamstrings'], 'iso', 'br'),
  E('Reverse Hyperextension', 'machine', 'lowerback', ['glutes'], 'iso'),
  E('Good Morning', 'barbell', 'hamstrings', ['lowerback', 'glutes'], 'comp'),
  E('Barbell Shrug', 'barbell', 'traps', ['forearms'], 'iso'),
  E('Dumbbell Shrug', 'dumbbell', 'traps', ['forearms'], 'iso'),
  E('Trap Bar Shrug', 'trapbar', 'traps', ['forearms'], 'iso'),
  E('Cable Shrug', 'cable', 'traps', [], 'iso'),
  E('Machine Shrug', 'machine', 'traps', [], 'iso'),

  // ---------- SHOULDERS ----------
  E('Standing Overhead Press', 'barbell', 'shoulders', ['triceps'], 'comp'),
  E('Seated Barbell Overhead Press', 'barbell', 'shoulders', ['triceps'], 'comp'),
  E('Push Press', 'barbell', 'shoulders', ['triceps', 'quads'], 'comp'),
  E('Behind-the-Neck Press', 'barbell', 'shoulders', ['triceps'], 'comp'),
  E('Dumbbell Shoulder Press', 'dumbbell', 'shoulders', ['triceps'], 'comp'),
  E('Seated Dumbbell Shoulder Press', 'dumbbell', 'shoulders', ['triceps'], 'comp'),
  E('Arnold Press', 'dumbbell', 'shoulders', ['triceps'], 'comp'),
  E('Machine Shoulder Press', 'machine', 'shoulders', ['triceps'], 'comp'),
  E('Smith Machine Shoulder Press', 'smith', 'shoulders', ['triceps'], 'comp'),
  E('Landmine Press', 'barbell', 'shoulders', ['triceps', 'chest'], 'comp'),
  E('Dumbbell Lateral Raise', 'dumbbell', 'shoulders', [], 'iso'),
  E('Cable Lateral Raise', 'cable', 'shoulders', [], 'iso'),
  E('Machine Lateral Raise', 'machine', 'shoulders', [], 'iso'),
  E('Leaning Cable Lateral Raise', 'cable', 'shoulders', [], 'iso'),
  E('Dumbbell Front Raise', 'dumbbell', 'shoulders', [], 'iso'),
  E('Cable Front Raise', 'cable', 'shoulders', [], 'iso'),
  E('Plate Front Raise', 'plate', 'shoulders', [], 'iso'),
  E('Dumbbell Rear Delt Fly', 'dumbbell', 'reardelts', ['upperback'], 'iso'),
  E('Reverse Pec Deck', 'machine', 'reardelts', ['upperback'], 'iso'),
  E('Cable Rear Delt Fly', 'cable', 'reardelts', ['upperback'], 'iso'),
  E('Face Pull', 'cable', 'reardelts', ['traps', 'upperback'], 'iso'),
  E('Barbell Upright Row', 'barbell', 'shoulders', ['traps'], 'comp'),
  E('Cable Upright Row', 'cable', 'shoulders', ['traps'], 'comp'),
  E('Handstand Push-Up', 'bodyweight', 'shoulders', ['triceps'], 'comp', 'br'),
  E('Pike Push-Up', 'bodyweight', 'shoulders', ['triceps'], 'comp', 'br'),
  E('Band Pull-Apart', 'band', 'reardelts', ['upperback'], 'iso'),

  // ---------- BICEPS ----------
  E('Barbell Curl', 'barbell', 'biceps', ['forearms'], 'iso'),
  E('EZ-Bar Curl', 'ezbar', 'biceps', ['forearms'], 'iso'),
  E('Barbell 21s', 'barbell', 'biceps', [], 'iso'),
  E('Dumbbell Curl', 'dumbbell', 'biceps', ['forearms'], 'iso'),
  E('Alternating Dumbbell Curl', 'dumbbell', 'biceps', ['forearms'], 'iso'),
  E('Hammer Curl', 'dumbbell', 'biceps', ['forearms'], 'iso'),
  E('Incline Dumbbell Curl', 'dumbbell', 'biceps', [], 'iso'),
  E('Concentration Curl', 'dumbbell', 'biceps', [], 'iso'),
  E('Spider Curl', 'dumbbell', 'biceps', [], 'iso'),
  E('Zottman Curl', 'dumbbell', 'biceps', ['forearms'], 'iso'),
  E('Preacher Curl', 'ezbar', 'biceps', [], 'iso'),
  E('Machine Preacher Curl', 'machine', 'biceps', [], 'iso'),
  E('Cable Curl', 'cable', 'biceps', ['forearms'], 'iso'),
  E('Cable Rope Hammer Curl', 'cable', 'biceps', ['forearms'], 'iso'),
  E('Bayesian Cable Curl', 'cable', 'biceps', [], 'iso'),
  E('Reverse Curl', 'ezbar', 'forearms', ['biceps'], 'iso'),

  // ---------- TRICEPS ----------
  E('Close-Grip Bench Press', 'barbell', 'triceps', ['chest', 'shoulders'], 'comp'),
  E('JM Press', 'barbell', 'triceps', ['chest'], 'comp'),
  E('Skull Crusher', 'ezbar', 'triceps', [], 'iso'),
  E('Tate Press', 'dumbbell', 'triceps', [], 'iso'),
  E('Dumbbell Overhead Triceps Extension', 'dumbbell', 'triceps', [], 'iso'),
  E('Single-Arm Overhead Triceps Extension', 'dumbbell', 'triceps', [], 'iso'),
  E('Cable Triceps Pushdown', 'cable', 'triceps', [], 'iso'),
  E('Rope Triceps Pushdown', 'cable', 'triceps', [], 'iso'),
  E('Reverse-Grip Pushdown', 'cable', 'triceps', [], 'iso'),
  E('Overhead Cable Triceps Extension', 'cable', 'triceps', [], 'iso'),
  E('Cable Triceps Kickback', 'cable', 'triceps', [], 'iso'),
  E('Dumbbell Triceps Kickback', 'dumbbell', 'triceps', [], 'iso'),
  E('Machine Triceps Extension', 'machine', 'triceps', [], 'iso'),
  E('Bench Dip', 'bodyweight', 'triceps', ['chest'], 'comp', 'br'),
  E('Diamond Push-Up', 'bodyweight', 'triceps', ['chest'], 'comp', 'br'),

  // ---------- FOREARMS / GRIP ----------
  E('Barbell Wrist Curl', 'barbell', 'forearms', [], 'iso'),
  E('Barbell Reverse Wrist Curl', 'barbell', 'forearms', [], 'iso'),
  E('Dumbbell Wrist Curl', 'dumbbell', 'forearms', [], 'iso'),
  E('Cable Reverse Curl', 'cable', 'forearms', ['biceps'], 'iso'),
  E('Wrist Roller', 'other', 'forearms', [], 'iso', 'dur'),
  E("Farmer's Walk", 'dumbbell', 'forearms', ['traps', 'fullbody'], 'comp', 'dur'),
  E('Plate Pinch Hold', 'plate', 'forearms', [], 'iso', 'dur'),
  E('Dead Hang', 'bodyweight', 'forearms', ['lats'], 'iso', 'dur'),

  // ---------- QUADS ----------
  E('Barbell Back Squat', 'barbell', 'quads', ['glutes', 'hamstrings', 'lowerback'], 'comp'),
  E('Barbell Front Squat', 'barbell', 'quads', ['glutes', 'abs'], 'comp'),
  E('Box Squat', 'barbell', 'quads', ['glutes', 'hamstrings'], 'comp'),
  E('Pause Squat', 'barbell', 'quads', ['glutes'], 'comp'),
  E('Zercher Squat', 'barbell', 'quads', ['glutes', 'abs'], 'comp'),
  E('Smith Machine Squat', 'smith', 'quads', ['glutes'], 'comp'),
  E('Hack Squat Machine', 'machine', 'quads', ['glutes'], 'comp'),
  E('Pendulum Squat', 'machine', 'quads', ['glutes'], 'comp'),
  E('Belt Squat', 'machine', 'quads', ['glutes'], 'comp'),
  E('Leg Press', 'machine', 'quads', ['glutes', 'hamstrings'], 'comp'),
  E('Single-Leg Press', 'machine', 'quads', ['glutes'], 'comp'),
  E('Leg Extension', 'machine', 'quads', [], 'iso'),
  E('Single-Leg Extension', 'machine', 'quads', [], 'iso'),
  E('Goblet Squat', 'kettlebell', 'quads', ['glutes', 'abs'], 'comp'),
  E('Bulgarian Split Squat', 'dumbbell', 'quads', ['glutes'], 'comp'),
  E('Walking Lunge', 'dumbbell', 'quads', ['glutes'], 'comp'),
  E('Reverse Lunge', 'dumbbell', 'quads', ['glutes'], 'comp'),
  E('Forward Lunge', 'dumbbell', 'quads', ['glutes'], 'comp'),
  E('Curtsy Lunge', 'dumbbell', 'glutes', ['quads', 'abductors'], 'comp'),
  E('Step-Up', 'dumbbell', 'quads', ['glutes'], 'comp'),
  E('Sissy Squat', 'bodyweight', 'quads', [], 'iso', 'br'),
  E('Wall Sit', 'bodyweight', 'quads', [], 'iso', 'dur'),
  E('Air Squat', 'bodyweight', 'quads', ['glutes'], 'comp', 'br'),
  E('Pistol Squat', 'bodyweight', 'quads', ['glutes'], 'comp', 'br'),

  // ---------- HAMSTRINGS ----------
  E('Romanian Deadlift', 'barbell', 'hamstrings', ['glutes', 'lowerback'], 'comp'),
  E('Dumbbell Romanian Deadlift', 'dumbbell', 'hamstrings', ['glutes'], 'comp'),
  E('Single-Leg Romanian Deadlift', 'dumbbell', 'hamstrings', ['glutes'], 'comp'),
  E('Stiff-Leg Deadlift', 'barbell', 'hamstrings', ['lowerback'], 'comp'),
  E('Lying Leg Curl', 'machine', 'hamstrings', ['calves'], 'iso'),
  E('Seated Leg Curl', 'machine', 'hamstrings', [], 'iso'),
  E('Standing Leg Curl', 'machine', 'hamstrings', [], 'iso'),
  E('Single-Leg Curl', 'machine', 'hamstrings', [], 'iso'),
  E('Nordic Hamstring Curl', 'bodyweight', 'hamstrings', [], 'iso', 'br'),
  E('Glute-Ham Raise', 'bodyweight', 'hamstrings', ['glutes'], 'comp', 'br'),
  E('Cable Pull-Through', 'cable', 'glutes', ['hamstrings'], 'comp'),

  // ---------- GLUTES / HIPS ----------
  E('Barbell Hip Thrust', 'barbell', 'glutes', ['hamstrings'], 'comp'),
  E('Machine Hip Thrust', 'machine', 'glutes', ['hamstrings'], 'comp'),
  E('Single-Leg Hip Thrust', 'bodyweight', 'glutes', ['hamstrings'], 'comp', 'br'),
  E('Glute Bridge', 'barbell', 'glutes', ['hamstrings'], 'comp'),
  E('Frog Pump', 'bodyweight', 'glutes', [], 'iso', 'br'),
  E('Cable Glute Kickback', 'cable', 'glutes', [], 'iso'),
  E('Machine Glute Kickback', 'machine', 'glutes', [], 'iso'),
  E('Hip Abduction Machine', 'machine', 'abductors', ['glutes'], 'iso'),
  E('Hip Adduction Machine', 'machine', 'adductors', [], 'iso'),
  E('Banded Lateral Walk', 'band', 'abductors', ['glutes'], 'iso', 'dur'),
  E('Copenhagen Plank', 'bodyweight', 'adductors', ['abs'], 'iso', 'dur'),

  // ---------- CALVES ----------
  E('Standing Calf Raise', 'machine', 'calves', [], 'iso'),
  E('Seated Calf Raise', 'machine', 'calves', [], 'iso'),
  E('Leg Press Calf Raise', 'machine', 'calves', [], 'iso'),
  E('Smith Machine Calf Raise', 'smith', 'calves', [], 'iso'),
  E('Donkey Calf Raise', 'machine', 'calves', [], 'iso'),
  E('Single-Leg Dumbbell Calf Raise', 'dumbbell', 'calves', [], 'iso'),

  // ---------- ABS / CORE ----------
  E('Plank', 'bodyweight', 'abs', ['obliques'], 'iso', 'dur'),
  E('Side Plank', 'bodyweight', 'obliques', ['abs'], 'iso', 'dur'),
  E('Hollow Body Hold', 'bodyweight', 'abs', [], 'iso', 'dur'),
  E('Dead Bug', 'bodyweight', 'abs', [], 'iso', 'br'),
  E('Crunch', 'bodyweight', 'abs', [], 'iso', 'br'),
  E('Sit-Up', 'bodyweight', 'abs', ['obliques'], 'iso', 'br'),
  E('Decline Sit-Up', 'bodyweight', 'abs', [], 'iso', 'br'),
  E('Bicycle Crunch', 'bodyweight', 'obliques', ['abs'], 'iso', 'br'),
  E('V-Up', 'bodyweight', 'abs', [], 'iso', 'br'),
  E('Flutter Kicks', 'bodyweight', 'abs', [], 'iso', 'dur'),
  E('Hanging Leg Raise', 'bodyweight', 'abs', ['forearms'], 'iso', 'br'),
  E('Hanging Knee Raise', 'bodyweight', 'abs', ['forearms'], 'iso', 'br'),
  E('Toes to Bar', 'bodyweight', 'abs', ['lats'], 'comp', 'br'),
  E("Captain's Chair Knee Raise", 'machine', 'abs', [], 'iso', 'br'),
  E('Dragon Flag', 'bodyweight', 'abs', [], 'iso', 'br'),
  E('Ab Wheel Rollout', 'other', 'abs', ['lats'], 'comp', 'br'),
  E('Cable Crunch', 'cable', 'abs', [], 'iso'),
  E('Machine Crunch', 'machine', 'abs', [], 'iso'),
  E('Russian Twist', 'plate', 'obliques', ['abs'], 'iso', 'br'),
  E('Cable Woodchop', 'cable', 'obliques', ['abs'], 'iso'),
  E('Pallof Press', 'cable', 'obliques', ['abs'], 'iso'),
  E('Landmine Twist', 'barbell', 'obliques', ['abs'], 'iso'),
  E('Dumbbell Side Bend', 'dumbbell', 'obliques', [], 'iso'),
  E('Mountain Climber', 'bodyweight', 'abs', ['cardio'], 'comp', 'dur'),

  // ---------- OLYMPIC / POWER / FULL BODY ----------
  E('Power Clean', 'barbell', 'fullbody', ['traps', 'quads', 'glutes'], 'comp'),
  E('Hang Clean', 'barbell', 'fullbody', ['traps', 'hamstrings'], 'comp'),
  E('Clean and Jerk', 'barbell', 'fullbody', ['shoulders', 'quads'], 'comp'),
  E('Snatch', 'barbell', 'fullbody', ['shoulders', 'traps'], 'comp'),
  E('Hang Snatch', 'barbell', 'fullbody', ['shoulders', 'traps'], 'comp'),
  E('Push Jerk', 'barbell', 'shoulders', ['quads', 'triceps'], 'comp'),
  E('Barbell Thruster', 'barbell', 'fullbody', ['quads', 'shoulders'], 'comp'),
  E('Kettlebell Swing', 'kettlebell', 'glutes', ['hamstrings', 'lowerback'], 'comp'),
  E('Kettlebell Clean and Press', 'kettlebell', 'fullbody', ['shoulders'], 'comp'),
  E('Kettlebell Snatch', 'kettlebell', 'fullbody', ['shoulders'], 'comp'),
  E('Turkish Get-Up', 'kettlebell', 'fullbody', ['abs', 'shoulders'], 'comp'),
  E('Burpee', 'bodyweight', 'fullbody', ['cardio'], 'comp', 'br'),
  E('Man Maker', 'dumbbell', 'fullbody', ['cardio'], 'comp', 'br'),
  E('Box Jump', 'bodyweight', 'quads', ['glutes', 'calves'], 'comp', 'br'),
  E('Broad Jump', 'bodyweight', 'quads', ['glutes'], 'comp', 'br'),
  E('Sled Push', 'sled', 'quads', ['glutes', 'cardio'], 'comp', 'cardio'),
  E('Sled Pull', 'sled', 'hamstrings', ['upperback', 'cardio'], 'comp', 'cardio'),
  E('Battle Ropes', 'other', 'shoulders', ['cardio', 'abs'], 'comp', 'dur'),
  E('Medicine Ball Slam', 'medball', 'fullbody', ['abs'], 'comp', 'br'),
  E('Wall Ball', 'medball', 'fullbody', ['quads', 'shoulders'], 'comp', 'br'),

  // ---------- NECK ----------
  E('Neck Curl', 'plate', 'neck', [], 'iso'),
  E('Neck Extension', 'plate', 'neck', [], 'iso'),
  E('Neck Harness Extension', 'other', 'neck', [], 'iso'),

  // ---------- CARDIO ----------
  E('Treadmill Run', 'cardio', 'cardio', [], 'comp', 'cardio'),
  E('Treadmill Incline Walk', 'cardio', 'cardio', ['calves', 'glutes'], 'comp', 'cardio'),
  E('Outdoor Run', 'other', 'cardio', [], 'comp', 'cardio'),
  E('Stationary Bike', 'cardio', 'cardio', ['quads'], 'comp', 'cardio'),
  E('Assault Bike', 'cardio', 'cardio', ['fullbody'], 'comp', 'cardio'),
  E('Outdoor Cycling', 'other', 'cardio', ['quads'], 'comp', 'cardio'),
  E('Rowing Machine', 'cardio', 'cardio', ['upperback', 'quads'], 'comp', 'cardio'),
  E('SkiErg', 'cardio', 'cardio', ['lats', 'abs'], 'comp', 'cardio'),
  E('Elliptical', 'cardio', 'cardio', [], 'comp', 'cardio'),
  E('Stair Climber', 'cardio', 'cardio', ['glutes', 'calves'], 'comp', 'cardio'),
  E('Jump Rope', 'other', 'cardio', ['calves'], 'comp', 'cardio'),
  E('Swimming', 'other', 'cardio', ['fullbody'], 'comp', 'cardio'),
  E('Incline Walk (Outdoor)', 'other', 'cardio', ['calves'], 'comp', 'cardio'),

  // ---------- MOBILITY / OTHER ----------
  E('Foam Rolling', 'other', 'fullbody', [], 'iso', 'dur'),
  E('Static Stretching', 'other', 'fullbody', [], 'iso', 'dur'),
  E('Hip Flexor Stretch', 'other', 'fullbody', [], 'iso', 'dur'),
  E('Thoracic Extension', 'other', 'upperback', [], 'iso', 'dur'),
];

export const LIBRARY_VERSION = 2;
